apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: lm-mpi-job
spec:
  minAvailable: 4
  schedulerName: volcano
  plugins:
    mpi: ["--master=mpilauncher","--worker=mpiworker","--port=2022"]
    ssh: ["--ssh-key-file-path=/home/sshuser/.ssh"]
  tasks:
    - replicas: 1
      name: mpilauncher
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
            - args:
                - /usr/bin/bash
                - -c
                - |
                 set -x && \
                 /usr/sbin/sshd -f /opt/ssh/sshd_config \
                 && mpirun --prtemca plm_ssh_args "-p 2022" \
                    --mca pml cm --mca mtl ofi --mca mtl_ofi_provider_include tcp \
                    --map-by 'ppr:1:node' \
                    -x FI_HOOK=monitor -x FI_LOG_LEVEL=trace \
                    --hostfile /etc/volcano/mpiworker.host \
                    /opt/osu/mpi/collective/osu_alltoall -m :4194304 -i 1000
              image: harbor.pt.horizon-opencube.eu/baseimages/rt-mpi:latest
              name: mpilauncher
              securityContext:
                runAsUser: 1001
                runAsGroup: 1001
              ports:
                - containerPort: 2022
                  name: mpijob-port
              workingDir: /home
              volumeMounts:
                - name: tmp
                  mountPath: /dev/shm
          restartPolicy: OnFailure
          volumes:
          - name: tmp
            emptyDir:
              medium: Memory
              sizeLimit: 4G
    - replicas: 4
      name: mpiworker
      template:
        metadata:
          labels:
            app: mpiworker
        spec:
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          terminationGracePeriodSeconds: 5
          volumes:
          containers:
            - args:
                - /usr/sbin/sshd
                - -f
                - /opt/ssh/sshd_config
                - -D
              image: harbor.pt.horizon-opencube.eu/example-apps/osu:latest
              name: mpiworker
              ports:
                - containerPort: 2022
                  name: mpijob-port
              workingDir: /home
              volumeMounts:
              - name: tmp
                mountPath: /dev/shm
          initContainers:
            - name: sampler
              image: harbor.pt.horizon-opencube.eu/baseimages/rt-libfabric:latest
              # Setting restartPolicy: Always makes this a sidecar container.
              restartPolicy: Always
              args:
                - /usr/bin/bash
                - -c 
                - |
                  mkdir --parents /dev/shm/ofi && \
                  fi_mon_sampler -w 1000 -v \
                    -f influx \
                    -r "http://influxdb-service:8181/api/v3/write_lp?db=ofi" \
                    /dev/shm/ofi
              volumeMounts:
                - name: tmp
                  mountPath: /dev/shm
              env:
              - name: TOKEN
                valueFrom:
                  secretKeyRef:
                    name: influxdb-secret
                    key: token
              - name: MON_SAMPLER_REMOTE_HEADERS
                value: "Authorization: Bearer $(TOKEN)"
          restartPolicy: OnFailure
          volumes:
          - name: tmp
            emptyDir:
              medium: Memory
              sizeLimit: 4G