name: publish-site
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install properdocs properdocs-literate-nav properdocs-theme-readthedocs

    - name: Build site
      id: build
      run: |
        properdocs build

    - name: Upload artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4